package com.movievault.model;

public enum GenreName {
    ACTION, COMEDY, DRAMA, HORROR, SCI_FI, THRILLER, ROMANCE,
    ANIMATION, DOCUMENTARY, FANTASY, CRIME, ADVENTURE, MYSTERY,
    WESTERN, MUSICAL, WAR, BIOGRAPHY, HISTORY, FAMILY, SPORT
}
